### ISSUE TITLE
Modifications is lost when aborting with `CTRL-C`

### ISSUE THREAD

**Issue by SRachamim** [gustavopch/tsc-files#13]
I'm using `tsc-files` as a Husky step on `pre-commit`.

Turns out `tsc-files` changes the file system in order to work. If you'll abort the script (with `CTRL-C`) you'll lose your modifications!

At least write it on the readme. Better is to actually bracket this dangerous action.

**Comment by gustavopch** [comment]
@SRachamim It's already mentioned that a file is created next to `tsconfig.json`:
> they will be put at the files property of a temporary config that will be generated next to your original `tsconfig.json`
> (https://github.com/gustavopch/tsc-files#how-it-works)

How would you write it to make it clearer? Perhaps a "Note: if you interrupt the process, the temporary config will be left in your file system"?

**Comment by SRachamim** [comment]
I mean, the project files are lost.

**Comment by gustavopch** [comment]
@SRachamim I wasn't able to reproduce. I'm reviewing the source code and the only file that's deleted is the temp config that's generated by `tsc-files`. I can't see how `tsc-files` could delete any other project files. Do you have any idea what may be wrong by reading the source code?

**Comment by SRachamim** [comment]
It may be a mistake to blame `tsc-files`. Is it possible that `husky` or `lint-staged` are responsible to this issue?

**Comment by gustavopch** [comment]
@SRachamim That's possible.

**Comment by SRachamim** [comment]
I'll close it as I couldn't prove it is caused by `tsc-files`.

Sorry, and thanks for your time.
