### ISSUE TITLE
Cannot include .d.ts files as of v1.1.3

### ISSUE THREAD

**Issue by owenjs** [gustavopch/tsc-files#21]
I am using `tsc-files@1.1.3` with `lint-staged@^12.0.3`

```json
"lint-staged": {
    "src/**/*.+(ts|tsx)": "tsc-files --noEmit"
  }
```
 
Works fine until a typescript file is checked that has custom types in, then the tsc complier fails.

This is because `.d.ts` files are ignored from the `include` array in the tsconfig as of #18 

I have reverted back to v1.1.2 and followed the suggested fix in [#9](https://github.com/gustavopch/tsc-files/issues/9#issuecomment-642960412) and everything works. Here are my two tsconfigs:

```json
// tsconfig.base.json
{
  "compilerOptions": {
    ...
  },
  "include": [
    "./src/vite-env.d.ts"
  ]
}
```

```json
// tsconfig.json
{
  "extends": "./tsconfig.base.json",
  "include": [
    "./src"
  ]
}
```

`tsc-files -p tsconfig.base.json --noEmit`

It looks like we need an option to include certain files just for the `tsc-files` tool

**Comment by gustavopch** [comment]
This is the same as https://github.com/gustavopch/tsc-files/issues/20. I'm closing here so we can talk in a single place in the other issue. I'm aware of this problem, but I don't know yet what would be the best way to solve it without reverting #18.

**Comment by owenjs** [comment]
@gustavopch apologies for the duplication! Will follow the other thread for updates, thanks.

**Comment by gustavopch** [comment]
I'm locking so the discussion is centralized in #20.
