### ISSUE TITLE
Having `include` be an empty array breaks type definitions

### ISSUE THREAD

**Issue by deanolium** [gustavopch/tsc-files#23]
The recent change on v1.1.3 to set include to an empty array causes the underlying `tsc` to ignore declaration files, which means things like importing png files now comes up as errors.

This change is also broken on the automated testing, and so should *never* have been made a release. It should also be a toggle-able option rather than a forced change.

**Comment by deanolium** [comment]
Realised this is a duplicate of  [https://github.com/gustavopch/tsc-files/issues/20](https://github.com/gustavopch/tsc-files/issues/20) so closing

**Comment by gustavopch** [comment]
I'm locking so the discussion is centralized in #20.
