### ISSUE TITLE
Support ambient declarations

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [gustavopch/tsc-files#24]
Currently, ambient types are not found: https://github.com/s-h-a-d-o-w/repro-tsc-files-ambient

**Comment by gustavopch** [comment]
@s-h-a-d-o-w Seems to be the same as https://github.com/gustavopch/tsc-files/issues/20. Workaround here: https://github.com/gustavopch/tsc-files/issues/20#issuecomment-996124875.

**Comment by s-h-a-d-o-w** [comment]
Whoops, thanks!
(Searched for "ambient" and didn't see anything. 😅)
