### ISSUE TITLE
Make it possible to specify which includes to remove, rather than removing all

### ISSUE THREAD

**Issue by emattias** [gustavopch/tsc-files#31]
Our `include` in `tsconfig.json` looks something like this:

```json
  "include": [
    "app/**/*",
    "tests/**/*",
    "types/**/*",
    "lib/library-abc/**/*",
    "foo/**/*"
  ]
```

We dont want `app/**/*` and `tests/**/*` to be included when `tsc-files` runs in the git hook but the other ones have types needed for parts of our project.

One solution could be that you could send in to `tsc-files` which includes to remove rather than removing all includes, [like is done now](https://github.com/gustavopch/tsc-files/blob/master/lib/index.js#L39).

Maybe something like: 

```bash
tsc-files --remove-include="app/**/*" --remove-include="tests/**/*"`
```
or
```sh
tsc-files --remove-include="app/**/*,tests/**/*"`
```

**Comment by gustavopch** [comment]
Same as https://github.com/gustavopch/tsc-files/issues/20.
