### ISSUE TITLE
Commit on .js/.jsx files fails (.ts/.tsx is successful)

### ISSUE THREAD

**Issue by mkosir** [gustavopch/tsc-files#34]
Thanks for an awesome tool 🚀 

I'm having an issue, if I try to commit `.js`/`.jsx` type of file, error is thrown: 
`error TS5042: Option 'project' cannot be mixed with source files on a command line.`

It works as expected for all other type of files.
In tsconfig `allowJs` is set to `true`.

**Comment by gustavopch** [comment]
Thanks! Please show the command you're using. Also, check this: https://github.com/okonet/lint-staged/issues/468#issuecomment-605102567

**Comment by mkosir** [comment]
I'm running this command on staged files `"tsc-files --noEmit -p tsconfig.dev.json src/types/images.d.ts"`.
Error happens in [this repo](https://github.com/mkosir/react-demo-tab), since `.jsx` files are used. In order to reproduce it, try to commit [.tsx]() file (works as expected) and then try to commit one of the [.jsx] files, in which case error is thrown.

**Comment by AndrewWUw** [comment]
With lint-staged, you could filter and run different commands based on file extension. So you could add a section into your `package.json` similar to below:

```json
{
  "lint-staged": {
    "**/*.ts": "tsc-files --noEmit",
    "**/*.tsx": "tsc-files --noEmit",
    "**/*.js": <command to run>,
    "**/*.jsx": <command to run>,
  }
}
```

**Comment by mkosir** [comment]
@AndrewWUw thx 🙇‍♂️ , this approach make much sense 👍
