### ISSUE TITLE
After apply paths alias, I have Error ( error TS2307: Cannot find module '@shared/lib' or its corresponding type declarations.) in Next.js

### ISSUE THREAD

**Issue by with-key** [gustavopch/tsc-files#37]
i set monorepo (yarn workspaces), lint-staged in my project. 
also, basically set `tsc-files`.

but. has error. Is there any setting that I need to do?

![image](https://user-images.githubusercontent.com/66957178/169180750-ce2bff0a-85a4-47b1-97ab-969b8f0c519f.png)

```
"lint-staged": {
    "**/*.{tsx,ts}": [
      "eslint",
      "tsc-files --noEmit"
    ]
  },
```

**Comment by gustavopch** [comment]
Same as https://github.com/gustavopch/tsc-files/issues/20. You'll find explanation and workarounds there in the comments.
