### ISSUE TITLE
Cannot find module '.png' or its corresponding type declarations

### ISSUE THREAD

**Issue by rexkenley** [gustavopch/tsc-files#42]
I have a project with the following configuration.
![image](https://user-images.githubusercontent.com/10548251/180878841-ca289dd4-f19b-4f5a-a9ac-e8ded4fa6d2f.png)
![image](https://user-images.githubusercontent.com/10548251/180878935-fa95395c-fd12-46d1-8b18-4403fd6ef43f.png)

It is working fine in the terminal and vscode, but when I ran it through tsc-files it gives me an error.
![image](https://user-images.githubusercontent.com/10548251/180879097-25d3854e-4992-436e-a3c5-75bf4fbbc517.png)

It doesn't look like it is reading from the tsconfig.json file. What am I doing incorrectly?

Thanks!

**Comment by gustavopch** [comment]
Same as https://github.com/gustavopch/tsc-files/issues/20. You have to explicitly pass the ambient declarations file to `tsc-files`, e.g.: `tsc-files file-you-want-to-check.ts ambient-declarations.d.ts`.
