### ISSUE TITLE
failing on check just indicated file

### ISSUE THREAD

**Issue by brunubarbosa** [gustavopch/tsc-files#43]
Running the command `tsc-files --noEmit --pretty file.ts` I'm receiving an error due to problems in files that I didn't point

![image](https://user-images.githubusercontent.com/40932088/185727260-268cb8bd-5169-4392-aebc-71cf2165472c.png)

As it's shown in the print, I'm indicating `src/pages/SSHKeys/Summary/index.tsx` but I'm receiving a bunch of errors due to files like `src/components/Table/index.tsx` (I tested either with files that should fail the type check and files that shouldn't)

In example case my expected behavior is to ignore all files other than `src/pages/SSHKeys/Summary/index.tsx`

My environment:
Console: `git bash`
SO: Windows 11

script: `tsc-files --noEmit --pretty` (running on `lint-staged`)

Any idea?

**Comment by gustavopch** [comment]
I think it's loading other files as they are imported.

**Comment by brunubarbosa** [comment]
but why? it's not supposed to check just indicated files? why is it checking imported files?

**Comment by gustavopch** [comment]
`tsc-files` just passes the files provided as arguments to the `files` field of `tsconfig.json`. The rest is all how TypeScript itself works.

**Comment by brunubarbosa** [comment]
do you have a `tsconfig.json` working file example? it might be some config conflict

**Comment by gustavopch** [comment]
Unfortunately not. I'm not using `tsc-files` in any project currently.
