### ISSUE TITLE
tsc-files with yarn 3 pnp

### ISSUE THREAD

**Issue by DylanMerigaud** [gustavopch/tsc-files#44]
![image](https://user-images.githubusercontent.com/1936984/190405661-341da6ff-f2e6-4798-9905-b353b1d4f103.png)
![image](https://user-images.githubusercontent.com/1936984/190405722-509997b4-eadd-4753-bd8f-befe31668e18.png)

When I run the command with yarn PNP (V.3.2.3) (which doesn't produce node_modules), I don't have any log and it pass despite the fact that I have an error in the file.
As I can see when I run the command with npx, it create the temp config at the root of my project but doesn't resolve the library types but with yarn it doesn't even create the file.
Any clues?

**Comment by gustavopch** [comment]
It won't resolve library types unless they're either imported or explicitly passed to the CLI. Strange that it isn't creating the config file. I suggest you to copy the source of `tsc-files` (less than a hundred lines) to your own project so you can add some console logs and see what's going wrong.

**Comment by DylanMerigaud** [comment]
Thx for your feedback! I'll try this when I'll have time, but from what I can see it may be caused by this line since it doesn't exit with an error.
![image](https://user-images.githubusercontent.com/1936984/190412689-fe2167ef-1cd5-4b4d-8e2d-8bcd9cd353cd.png)

**Comment by DylanMerigaud** [comment]
@gustavopch 
![image](https://user-images.githubusercontent.com/1936984/190988005-8e0a77ae-6f04-40c4-962d-e6dfb7e9d956.png)
`const { status } = spawnSync(
  "tsc",
  ['-p', tmpTsconfigPath, ...remainingArgsToForward],
  { stdio: 'inherit' },
)`
I managed to make it work with this code, since Yarn PNP has no node_modules folder, nor .bin folder, I think you must execute the command without a path so yarn can resolve it for you.

Maybe we could do a fallback for the path with a code like this ?
`if (process.versions.pnp) {
  // do something with the PnP API ...
} else {
  // fallback
}`
(https://yarnpkg.com/advanced/pnpapi#processversionspnp)

**Comment by DylanMerigaud** [comment]
```
#!/bin/sh
if [ ! -f "$(dirname "$0")/_/husky.sh" ]; then
    exit 0
fi

. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
```
Btw here is my .husky/pre-commit file, you must use yarn there

**Comment by wmertens** [comment]
Same problem with pnpm, IMHO you shouldn't try to resolve tsc yourself ever.

**Comment by gustavopch** [comment]
@DylanMerigaud Sorry for the super long delay. Implemented your suggestion in https://github.com/gustavopch/tsc-files/releases/tag/v1.1.4, so I'm closing this issue.

@wmertens When I call `spawnSync('tsc')`, it doesn't find the binary because it's not installed globally.

**Comment by wmertens** [comment]
@gustavopch normally when you run the command, you run it via npm scripts so they will have the installed node_modules tsc in the path.

A script's job is not to find executables. It should accept whatever executable the user deems appropriate, as given by the `PATH`.
