### ISSUE TITLE
set "include" tsc config option to empty string to prevent normal include settings from applying

### ISSUE THREAD

**Issue by sjungwirth** [gustavopch/tsc-files#5]
my project has a tsconfig w/ an `include` option specified, but it seems the intent of this project is only to test specific files.

overwriting any `include` option in the base tsconfig will prevent unintended checking of other files.

**Comment by gustavopch** [comment]
@sjungwirth I'm not sure if I understand the issue. Are you afraid that `tsc-files` will mess your `tsconfig.json`? What do you believe should be changed to cover your use case?

**Comment by IPWright83** [comment]
If I understand correctly, this means that `tsc-files` isn't really going to save any time if `include` is being used then? 

> @sjungwirth Got it. Thanks for the detailed explanation.
> 
> I found [this article](https://dzone.com/articles/what-is-the-tsconfigjson-configuration-file) saying that:
> 
> > When both the `files` and `include` properties are specified, the compiler includes the union of the specified files.
> 
> So we should probably make sure we always omit the `include` property in the [generated config](https://github.com/gustavopch/tsc-files/blob/master/lib/index.js#L31-L38), right?

**Comment by gustavopch** [comment]
@IPWright83 I just tested here. Yes, all files in `include` would be processed in addition to the files explicitly passed to the CLI. Thanks for your PR.

**Comment by IPWright83** [comment]
@gustavopch thanks for merging quickly.
