### ISSUE TITLE
Incompatibility with vite/css modules

### ISSUE THREAD

**Issue by viveleroi** [gustavopch/tsc-files#51]
Just installed v1.1.3 into our vite-based project, in which we use CSS Modules. 
tsc-files must not be using the tsc-config properly or something that vite did to recognize css modules, because this linter fails when it reaches them:

```
app/components/buttons/buttons.tsx(10,20): error TS2307: Cannot find module './buttons.module.css' or its corresponding type declarations.
app/components/icons/icons.tsx(6,20): error TS2307: Cannot find module './icons.module.css' or its corresponding type declarations.
app/components/window/window.tsx(8,20): error TS2307: Cannot find module './window.module.css' or its corresponding type declarations.
```

When I run `tsc --noEmit` directly, it doesn't complain.

**Comment by gustavopch** [comment]
Same as https://github.com/gustavopch/tsc-files/issues/20.
