### ISSUE TITLE
tsc-files is failing because it isn't including type definitions

### ISSUE THREAD

**Issue by mosnicholas** [gustavopch/tsc-files#59]
https://github.com/gustavopch/tsc-files/blob/c01619fb0ff6eea957f322539e2a8d336c2900e6/cli.js#L56C15-L56C15

This line is overriding my tsconfig `include` array, which defines some project-specific types. These are important to help extend typescript definitions with local ones. Is there a reason this always overrides the include array?

**Comment by gustavopch** [comment]
If we don't override, all your types will be loaded instead of only the types from the specific files you want to check, defeating the purpose of this tool. It's discussed here: https://github.com/gustavopch/tsc-files/issues/20.

**Comment by mosnicholas** [comment]
Got it thank you @gustavopch
