### ISSUE TITLE
Does not work when tsconfig uses "include"

### ISSUE THREAD

**Issue by jamesopti** [gustavopch/tsc-files#9]
I'm trying to use this tool to generate a type definition file for a single entrypoint (there are many in my codebase that all share a single tsconfig.json).

**_Desired usage:_**

`npx tsc-files src/bundles/app1/index.ts`

**_TSConfig:_**

```json
{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es2015",
    "module": "es2015",
    "jsx": "react",
    "declaration": true,
    "emitDeclarationOnly": true,
    "experimentalDecorators": true,
    "outFile": "types/index",
    "strict": true,
    "noImplicitAny": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": ["src/**/*", "index.d.ts"],  <--- I WANT TO IGNORE THIS!
  "exclude": ["dist", "docs", "node_modules", "tmp"]
}
```

**Comment by gustavopch** [comment]
Hey @jamesopti. I'm not sure if `tsc-files` should be responsible for that. I mean, people may need to exclude arbitrary keys from their `tsconfig.json` files.

This tool is meant to be a tiny wrapper on top of the original `tsc` CLI with the sole purpose of providing a workaround for https://github.com/microsoft/TypeScript/issues/27379 while they don't fix that behavior in `tsc` itself, so adding extra flags or parameters is something I want to avoid as much as possible.

But I believe there's a much simpler way to solve your use case. You could have a `tsconfig.base.json` which would contain everything except the `include` key:
```json
{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es2015",
    "module": "es2015",
    "jsx": "react",
    "declaration": true,
    "emitDeclarationOnly": true,
    "experimentalDecorators": true,
    "outFile": "types/index",
    "strict": true,
    "noImplicitAny": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "exclude": ["dist", "docs", "node_modules", "tmp"]
}
```

So you'd call `tsc-files` with the `-p tsconfig.base.json` parameter. Then, you'd have `tsconfig.json`:
```json
{
  "extends": "./tsconfig.base.json",
  "include": ["src/**/*", "index.d.ts"]
}
```

**Comment by sjungwirth** [comment]
same issue I had in https://github.com/gustavopch/tsc-files/issues/5

**Comment by zomars** [comment]
We might need to make our own fork @KATT

**Comment by gustavopch** [comment]
It's not clear to me if there's anything wrong with the rationale and the solution that I provided in https://github.com/gustavopch/tsc-files/issues/9#issuecomment-642960412.

**Comment by zomars** [comment]
We just don't want to modify the tsconfig to accommodate to this tool. Nothing wrong really.

**Comment by gustavopch** [comment]
@zomars Thanks for your answer. My concern is that someone may need to remove `exclude`, then someone else may need to remove some items from `include` while keeping others, and so on. That is, it doesn't seem like simply adding a flag to remove `include` will solve all use cases. Adding that flag would just be what we call a _gambiarra_ in Brazil — the opposite of an elegant solution. The only solution that I can see that's able to conform to all possible use cases without bloating `tsc-files` and transforming it into a config editor is by using a separate config file.

**Comment by gustavopch** [comment]
OK, now I actually understand the issue.

When you run `tsc-files src/foo.ts`, you want to process `src/foo.ts` alone, but if you have `"include": ["src"]` in your `tsconfig.json`, it processes everything in the `src` folder, not just `src/foo.ts`. That behavior is a bug because it defeats the whole purpose of this tool — and so it should neither need a flag nor be extensible to other config properties.

I've just merged https://github.com/gustavopch/tsc-files/pull/18 which solves it in a very simple way.
